-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 
-- Tiempo de generación: 06-08-2025 a las 21:16:02
-- Versión del servidor: 11.4.7-MariaDB
-- Versión de PHP: 7.2.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: ``
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `comentarios`
--

CREATE TABLE `comentarios` (
  `id` int(11) NOT NULL,
  `nombre_usuario` varchar(50) DEFAULT NULL,
  `imagen_perfil` varchar(255) DEFAULT NULL,
  `comentario` text DEFAULT NULL,
  `fecha` datetime DEFAULT NULL,
  `categoria` varchar(50) DEFAULT NULL,
  `respuesta_a` int(11) DEFAULT NULL,
  `likes` int(11) DEFAULT 0,
  `dislikes` int(11) DEFAULT 0
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Volcado de datos para la tabla `comentarios`
--

INSERT INTO `comentarios` (`id`, `nombre_usuario`, `imagen_perfil`, `comentario`, `fecha`, `categoria`, `respuesta_a`, `likes`, `dislikes`) VALUES
(3, 'StopAmister595', 'imagenes_perfil/marian.jpg', 'Hola', '2025-07-16 21:02:45', 'foro_general', NULL, 0, 0),
(4, 'Homero', 'imagenes_perfil/1000140057.jpg', 'Hola', '2025-07-16 21:04:43', 'foro_general', NULL, 0, 0),
(51, 'Homero ', 'imagenes_perfil/1000155868.jpg', 'No soy furro', '2025-08-05 17:33:01', 'foro_general', 0, 0, 0),
(52, 'Ancient_Bey900', 'imagenes_perfil/1000025521.jpg', 'Â¡LOS DEL CANAL 12 DE LA TELEVISIÃ“N DE AQUI DE DURANGO ME APUNTARON CON UNA PISTOLA! LOS NARCOS SE VAN A MORIR A OCHOA LO MATARON A BALAZOS Y MI PAPÃ ES FOX PRESIDENTE DE MEXICO', '2025-08-05 19:10:58', 'foro_general', 0, 0, 0),
(30, 'dotkras', 'imagenes_perfil/buzz.jfif', 'good', '2025-07-31 10:40:45', 'foro_general', 0, 0, 0),
(33, 'Miguel', 'imagenes_perfil/20250221_123805.jpg', 'Hola', '2025-08-01 05:55:26', 'foro_general', 0, 0, 0),
(42, 'K', 'imagenes_perfil/1000037307.jpg', 'Me quiero ir ðŸ˜« a mi casita', '2025-08-04 07:56:57', 'foro_general', 0, 0, 0);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `InteligenciasArtificiales`
--

CREATE TABLE `InteligenciasArtificiales` (
  `id` int(11) NOT NULL,
  `nombre` varchar(100) DEFAULT NULL,
  `numero_servicio` varchar(100) DEFAULT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `funcion_principal` text DEFAULT NULL,
  `sitio_activacion` varchar(100) DEFAULT NULL,
  `fecha_activacion` date DEFAULT NULL,
  `descripcion` text DEFAULT NULL,
  `imagen` varchar(255) DEFAULT NULL,
  `categoria` varchar(100) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Volcado de datos para la tabla `InteligenciasArtificiales`
--

INSERT INTO `InteligenciasArtificiales` (`id`, `nombre`, `numero_servicio`, `avatar`, `funcion_principal`, `sitio_activacion`, `fecha_activacion`, `descripcion`, `imagen`, `categoria`) VALUES
(1, 'Cortana', 'CTN 0452-9', 'Doctora Halsey', 'Software de infiltración', 'Reach', '2549-11-07', 'Cortana, una IA libre y volitiva, diseñada originalmente por la Dra. Catherine Halsey, representa la notable combinación de una programación de intrusión de software extremadamente avanzada con el carisma, la empatía y las ventajas antropomórficas de una personalidad humana. Mordaz, ingeniosa y segura de sus capacidades únicas, Cortana sirvió junto a John-117 en las últimas semanas de la Guerra del Covenant, durante el crucial Evento Halo que finalmente provocó el fin del conflicto\r\n\r\nEl avatar holográfico elegido por Cortana es el de una mujer de piel azul, cubierta de símbolos de datos que se desplazan. La selección de este avatar no fue arbitraria, ya que se parece mucho a una joven Halsey, quien creó en secreto la IA utilizando la plantilla neuronal de su propio cerebro, obtenida mediante procedimientos ilegales de clonación flash. Si bien esta metodología fue extremadamente controvertida para quienes la conocían, la mente de Halsey es una de las razones por las que Cortana fue la IA más poderosa jamás desarrollada por la humanidad. Capaz de transferir su personalidad central a cualquier sistema informático de suficiente complejidad y potencia de procesamiento, teóricamente tenía acceso a recursos ilimitados. Sin embargo, como todas las demás IA inteligentes, la vida de Cortana estaba regida por un parámetro de siete años, al final del cual tendría que ser eliminada para evitar un descenso inevitable a la caótica locura de la desenfreno.', 'https://i.pinimg.com/736x/ac/3f/12/ac3f12acc6c4270794298b82b7a09e6f.jpg', 'Jefe Maestro y Cortana'),
(2, 'Isabel', 'ISA 1307-2', 'Operadora Logistica ', 'Logistica, Diseño industrial', '[Desconocido]', '2556-03-18', 'Isabel es una IA inteligente de quinta generación que actualmente administra las operaciones a bordo del UNSC Spirit of Fire. Originalmente fue asignada al Puesto de Investigación Henry Lamb para ayudar en el trabajo del investigador en la construcción extragaláctica conocida como el Arca, pero esto se vio interrumpido por el cierre inesperado del portal a la Tierra y el repentino y violento asalto de los Desterrados. Ahora se le ha dado la oportunidad de contraatacar a este nuevo enemigo con el control de las vastas reservas de material militar y potencial del Spirit of Fire, aunque queda por ver si puede concentrar su venganza de forma productiva. A pesar de esta incertidumbre, su actuación a bordo del Spirit of Fire ha sido nada menos que espectacular; su cuidadosa planificación y sus habilidades incluso llevaron a un asalto decisivo a la nave insignia de los Desterrados, Enduring Conviction.', 'https://www.pcgamesn.com/wp-content/sites/pcgamesn/legacy/isabel-halo-wars-2-550x309.jpg', 'Spirit of fire'),
(3, 'Serina ', 'SNA 1292-4', 'Directora de nave', 'Planificación de operaciones, cientifica', '[Desconocido]', '2530-01-07', 'Una IA inteligente de tercera generación asignada al Spirit of Fire poco después de su creación, Serina administró el despliegue de fuerzas en la superficie de Harvest y dirigió con éxito campañas posteriores tanto en Arcadia como en un misterioso mundo artificial conocido como Trove. Fue en esta instalación donde Serina realizó el primer análisis detallado del Flood en la historia del UNSC, aunque sus informes nunca llegaron a la Tierra. Mientras el Spirit of Fire estaba varado en el espacio profundo, Serina inició la dispensación final con la ayuda del profesor Anders, ansiosa por evitar cualquier efecto catastrófico de su propia desenfreno. Incluso después de su partida, el legado de Serina a bordo del Spirit of Fire está innegablemente presente, habiendo iniciado silenciosamente sus fábricas de producción durante el largo criosueño de la tripulación, un acto fundamental que proporcionó las enormes reservas de activos militares que eventualmente necesitarían para enfrentarse a la amenaza de los Desterrados', 'https://assets.mycast.io/characters/serina-7287244-normal.jpg?1656973140', 'Spirit of fire '),
(4, 'Roland', 'RLD 0205-4', 'Piloto de la segunda guerra mundial', 'Gestión de naves, navegación', '[Desconocido]', '2557-12-05', 'Roland, un constructo de IA inteligente de quinta generación extremadamente capaz y competente, es el director formal y administrador logístico de la nave insignia Infinity de la UNSC, lo que lo convierte en uno de los IA humanos más importantes actualmente en servicio. Fiable y digno de confianza, el capitán Thomas Lasky a menudo ha confiado en la habilidad y la experiencia de Roland en el devastador proceso del ascenso de Cortana al poder.', 'https://halo.wiki.gallery/images/thumb/6/6d/H5G_Roland.png/800px-H5G_Roland.png', 'IA'),
(5, 'Gabriela', 'GBA 0983-6', 'Almirante UNSC', 'Directora de instalaciones logisticas', '[Desconocido]', '2552-05-24', 'Gabriela, una IA inteligente de quinta generación de la UNSC, es la cuidadora oficial del Puesto de Avanzada Discovery en la Tierra y fue diseñada explícitamente para contener un registro completo y único de toda la historia humana catalogada. Dirige todas las funciones y actividades de las instalaciones logísticas móviles, administrando sus numerosas exhibiciones y gestionando todas sus operaciones.', 'https://halo.wiki.gallery/images/thumb/b/b5/Gabriella.jpg/400px-Gabriella.jpg', 'IA'),
(6, 'Kalmiya', 'KMA 0991-X', 'Femenino', 'Analisis de datos, Cyberguerra', '[Desconocido]', '2537-03-19', 'Kalmiya, una notable IA inteligente de tercera generación, fue creada para probar técnicas y algoritmos que la Dra. Catherine Halsey perfeccionaría posteriormente para Cortana. Como parte de esta investigación, Kalmiya fue descompilada, editada selectivamente y reconstruida muchas veces a lo largo de los años. Cada iteración de Kalmiya era ligeramente diferente, pero solo Halsey pudo discernir los cambios sutiles en cada revisión. Halsey activó el protocolo de seguridad de Kalmiya durante la caída de Reach y la destruyó, aunque subrutinas y procesos independientes aún rondan los pasillos de los núcleos de datos supervivientes de la base CASTLE.', 'https://halo.wiki.gallery/images/thumb/a/ad/Enc22_Kalmiya.jpg/800px-Enc22_Kalmiya.jpg', 'IA'),
(7, 'Iona', 'IOA 7201-4', 'Femenino', 'Analisis de datos y soporte ', '[Desconocido]', '2551-01-24', 'La ONI desarrolló Iona como parte del programa OEUVRE, una poderosa IA de tercera generación de grado militar creada específicamente para el análisis operativo y el apoyo a misiones. Peculiar, ingeniosa, pero propensa a una profunda introspección, Iona fue asignada a varias naves de exploración de la ONI y elementos de combate de operaciones especiales, incluido el Equipo Negro Espartano. Fue desactivada después de siete años de servicio.', 'https://halo.wiki.gallery/images/c/c6/Halo_Saints_Testimony.jpg', 'IA'),
(8, 'Black Box ', 'BBX 8995-1', 'Cubo brillante', 'Psicologia, Cyberguerra', '[Desconocido]', '2252-08-17', 'Caja Negra es el asistente, confidente y hacker personal del almirante CINCONI Serin Osman. Un diseño de cuarta generación altamente avanzado, Caja Negra puede explotar los sistemas de comunicación desliespacial derivados de los Forerunner para gestionar múltiples actividades a través de distancias interestelares o dividir fragmentos semiautónomos para explotar las redes informáticas locales. Jugó un papel decisivo en asegurar la evacuación de Osman y el almirante Hood de la Tierra cuando llegaron las fuerzas de Cortana, aunque se desconoce su estado actual.', 'https://halo.wiki.gallery/images/8/84/Waypoint_-_Black-Box.jpg', 'IA'),
(9, 'Auntie Dot', 'ADT 6849-9', 'Patrón Geometrico', 'Tacticas, analisis de inteligencia ', '[Desconocido]', '2541-05-09', 'La tía Dot fue creada para servir como adjunta de supervisión de operaciones, proporcionando apoyo de inteligencia y actuando como enlace directo entre los equipos desplegados y sus oficiales al mando. Dot trabajó junto al coronel Urban Holland para ayudar a gestionar y dirigir varios destacamentos de las Fuerzas Especiales durante la caída de Reach, incluido el Equipo Noble Espartano. Es poco probable que los servidores en los que residía sobrevivieran a la devastación del planeta.', 'https://halo.wiki.gallery/images/thumb/f/f6/Auntie_Dot.jpg/800px-Auntie_Dot.jpg', 'IA'),
(10, 'Deja', 'DJA 0552-1', 'Diosa griega ', 'Educación,Investigación, Ciberseguridad.', '[Desconocido]', '2510-12-22', 'Como una IA no volitiva personalizada creada según los parámetros específicos de la Dra. Catherine Halsey, Déjà sirvió como asistente de investigación de Halsey durante muchos años y fue una de las instructoras principales de los niños SPARTAN-II durante su entrenamiento formativo. Déjà estaba en Reach cuando el planeta cayó ante el Covenant, pero debido a la gravedad del asalto a la base CASTILLO, es poco probable que sus grupos de servidores sobrevivieran a la lluvia radiactiva.', 'https://halo.wiki.gallery/images/1/1c/Deja_2.png', 'IA'),
(11, 'Superintendente (Vergil)', 'Nm/EAP/98458930/1244', 'Cara animada', 'Gestión de infraestructura, logistica', '[Desconocido]', '2512-12-19', 'El IA tonto de segunda generación que gestionaba una amplia gama de funciones municipales para la ciudad de Nueva Mombasa se llamaba simplemente el Superintendente. Sin embargo, dentro de la construcción había una subrutina llamada \"Vergil\", que contenía información crítica descubierta sobre el portal Forerunner enterrado bajo la ciudad. Cuando un Huragok absorbió esta entidad, se convirtió en un activo de Nivel 1 que la ONI buscaba desesperadamente adquirir.', 'https://halo.wiki.gallery/images/5/5d/Superintendant-alone.svg', 'IA'),
(12, 'Wellsley', 'WLS 3982-0', 'Duque de Wellington', 'Asistente de operaciones ODST', '[Desconocido]', '2469-05-01', 'Wellsley es una IA de cuarta generación, no volitiva, originalmente asignada para gestionar la logística del campo de batalla para el Mayor Antonio Silva y sus fuerzas ODST durante la Operación: BANDERA ROJA. Estacionado a bordo del Pillar of Autumn, Wellsley ayudó a dirigir los despliegues del UNSC durante el abordaje del Covenant y el conflicto que siguió en la superficie de Halo, pero se perdió cuando el mundo anillo fue destruido.', 'https://halo.wiki.gallery/images/thumb/1/10/HFR_Campaign_Escape_Wellsley.png/113px-HFR_Campaign_Escape_Wellsley.png', 'IA');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `personajes`
--

CREATE TABLE `personajes` (
  `id` int(11) NOT NULL,
  `nombre` varchar(100) DEFAULT NULL,
  `numero_servicio` varchar(50) DEFAULT NULL,
  `altura` int(11) DEFAULT NULL,
  `peso` decimal(5,2) DEFAULT NULL,
  `mundo_nacimiento` varchar(100) DEFAULT NULL,
  `rango` varchar(50) DEFAULT NULL,
  `fecha_nacimiento` date DEFAULT NULL,
  `descripcion` mediumtext DEFAULT NULL,
  `imagen` varchar(255) DEFAULT NULL,
  `categoria` varchar(50) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `personajes`
--

INSERT INTO `personajes` (`id`, `nombre`, `numero_servicio`, `altura`, `peso`, `mundo_nacimiento`, `rango`, `fecha_nacimiento`, `descripcion`, `imagen`, `categoria`) VALUES
(1, 'John-117', 'S-117', 218, '130.00', ' Eridanus II', ' Master Chief Petty Officer', '2511-03-07', 'Considerado por la mayoría como una leyenda viviente, el Jefe Maestro fue el individuo más importante durante la Guerra del Covenant, no solo porque jugó un papel decisivo en el final del conflicto, sino porque encarnaba un símbolo de esperanza inquebrantable en la hora más oscura de la humanidad. Estoico, impávido, profesional e intensamente concentrado en la tarea en cuestión, este espartano inspiraba asombro como un héroe mitológico de la historia antigua, pero con la presencia formativa de un tanque blindado\r\n\r\nSi bien es competente en todos los aspectos de las tácticas de infantería, así como en los fundamentos del combate aeroespacial de gravedad variable, una de las habilidades más notables de John-117 es el liderazgo: su capacidad para dirigir eficazmente destacamentos operativos que varían en tamaño, desde equipos de fuego hasta batallones completos. Hacia el final de la guerra, el personal del UNSC en todos los niveles generalmente se sometió a la experiencia y el intelecto estratégico de John-117, lo que le otorgó un nivel de autoridad que superó con creces su rango real. A menudo lidera el Equipo Azul, un equipo de ataque espartano que ha existido de una forma u otra desde los primeros días de la Guerra del Covenant\r\n\r\nComo soldado de pocas palabras, la preferencia del Jefe Maestro por la acción sobre el discurso a veces se considera imprudente, aunque esto es tanto producto de su determinación pura como una faceta del adoctrinamiento y entrenamiento de los SPARTAN-II. John-117 prioriza la misión por encima de todo. Aunque es muy protector con sus compañeros Spartans, es muy consciente de la necesidad de defender a la humanidad, sin importar el costo. Ha elegido aceptar este sacrificio y no espera menos de quienes sirven con él. A lo largo de su extensa carrera militar, John-117 ha logrado numerosas hazañas y ha demostrado un coraje inquebrantable que es nada menos que extraordinario. Sin embargo, largos años de guerra le han dado al Spartan un modo de pensar sombrío y serio, pero no han quebrado su resiliencia ni debilitado su compromiso de luchar por aquellos que no pueden luchar por sí mismos', 'https://halo.wiki.gallery/images/thumb/7/77/HINF_John-117_RenderCrop.png/400px-HINF_John-117_RenderCrop.png', 'Jefe Maestro y Cortana'),
(2, 'Jacob Keyes', '01928-19912-JK', 194, '96.20', 'Tierra', 'Capitán', '2495-02-08', 'Audaz, valiente e impulsado por el deber, Jacob Keyes fue un consumado comandante naval, que no solo participó en muchas batallas críticas a lo largo de la Guerra del Covenant, sino que también sirvió como profesor experimentado en la academia naval de Luna. Al principio de su carrera, una misión clasificada de la ONI con la Dra. Halsey resultó en una breve pero tempestuosa relación y en una hija, Miranda, aunque permanecerían distanciados en los años siguientes. En el último año de la guerra, Keyes jugó un papel importante en las batallas de Sigma Octanus IV y Reach, pero finalmente se vio obligado a llevar la UNSC Pillar of Autumn a Halo. Allí luchó junto al Jefe Maestro contra el Covenant para ayudar a asegurar el mundo anillo, aunque finalmente encontró su fin en las garras del Flood. A pesar de su trágico destino, Keyes dejó un legado perdurable en el corazón de su hija, quien se convirtió en una heroína fundamental en los últimos días de la guerra.', 'https://pm1.aminoapps.com/6454/658cb6d8824333304f98f82ddf9eeb00aaafda60_hq.jpg', 'Figuras notables'),
(3, 'Doctora Halsey', 'CC-409871', 170, '53.00', 'Endymion', 'Contratista Civíl', '2492-03-19', 'Contratada por la Oficina de Inteligencia Naval cuando era una joven prodigio, Catherine Halsey encabezó los proyectos ultrasecretos SPARTAN-II y MJOLNIR, así como la creación de Cortana. A pesar de la inmensa deuda moral contraída, estas acciones sirvieron finalmente para poner fin a la guerra con el Covenant, convirtiéndola en una de las figuras más importantes del siglo XXVI. Aunque su actitud a menudo se titula de arrogante, insensible y cruel, en privado alberga profundos arrepentimientos por el programa SPARTAN-II e intenta encontrar consuelo en el éxito objetivo del proyecto: la supervivencia de la humanidad. Externamente, tales luchas están bien ocultas bajo una pesada capa de autocomplacencia de que «el fin justifica los medios». El extenso conocimiento tecnológico y antropológico que ha acumulado tanto del Covenant como de los Forerunner la ha colocado invariablemente en varias coyunturas críticas en el desarrollo de la humanidad. Fue indispensable para el asalto de Infinity a Zeta Halo, con el fin de detener a la misma Al que creó para salvar a la humanidad', 'https://pm1.aminoapps.com/6912/9e29053ffd9bc67a972c9a34cf53ebaa0245497br1-600-493v2_hq.jpg', 'Figuras notables'),
(4, 'Comandante Miranda Keyes', '15972-19891-MK', 178, '68.50', 'Luna', 'Comandante', '2525-02-28', 'Desafiando a todos los escépticos al negarse a vivir a la sombra de su padre, Miranda Keyes fue una magistral comandante y estratega naval por derecho propio. A pesar de una estrecha relación con su padre, la carrera militar de Keyes no fue fácil, y fue constantemente acosada por acusaciones de nepotismo. Durante los enfrentamientos finales de la Guerra del Covenant, Keyes persiguió dos veces a las fuerzas del Covenant al desliespacio desde la Tierra. A pesar de luchar valientemente directamente contra el Covenant en numerosas batallas durante su carrera militar, finalmente fue asesinada por el Profeta de la Verdad, sacrificando su vida para salvar a un compañero soldado. Las acciones desinteresadas de Keyes contribuirían en última instancia a la victoria del UNSC contra el Covenant, asegurando un legado duradero propio.', 'https://halo.wiki.gallery/images/thumb/6/63/H2A_-_Miranda.png/1200px-H2A_-_Miranda.png', 'Figuras notables'),
(5, 'Sargento Mayor Johnson', '48789-20114-AJ', 187, '95.50', 'Tierra', 'Sargento Mayor', '2474-11-23', 'Avery Johnson, un veterano experimentado y curtido en la batalla del Cuerpo de Marines del UNSC, ha acumulado décadas de experiencia en combate tanto contra las fuerzas insurrectas humanas como contra el Covenant. A pesar de su actitud arrogante y su enfoque brusco y sensato del liderazgo, la lealtad de Johnson a la misión del UNSC y a la supervivencia de la humanidad significó que a menudo estuvo en el meollo de la acción, desempeñando un papel fundamental a lo largo de los conflictos del siglo XXVI. Su excepcional desempeño en el Cuerpo de Marines lo llevó a ser reclutado en el Proyecto: ORION, donde fue desplegado en operaciones clasificadas contra rebeldes humanos. Johnson finalmente sacrificó su vida, intentando disparar tácticamente Halo y detener el brote del Flood en el Arca, contribuyendo valientemente a la supervivencia de la humanidad al final de la Guerra del Covenant.', 'https://pm1.aminoapps.com/6350/ba664d18c369c0ce460887fe7c65914705407002_hq.jpg', 'Figuras notables'),
(6, 'Fernando Esparza ECHO-216', 'CC-434323', 180, '86.20', 'Charybdis IX', 'Contratista Civíl', '2518-05-07', 'Fernando Esparza formó parte del esfuerzo del UNSC para atacar la presencia de Cortana en Zeta Halo. Cuando los Desterrados emboscaron repentinamente a sus fuerzas y comenzaron a diezmarlas en número, Esparza permitió que el miedo superara al deber, comandando un Pelican para escapar. Esto resultó infructuoso y, mientras estaba a la deriva en el espacio, toda esperanza parecía perdida hasta que se topó con una señal que lo condujo hasta el Jefe Maestro. Inicialmente impulsado por el miedo y la necesidad de priorizar su supervivencia por encima de todo, Esparza descubrió un nuevo coraje mientras luchaba junto al Spartan en Zeta Halo. Durante su misión, fue capturado por el asesino de los Desterrados Jega \'Rdomnal y torturado dentro de la propia fortaleza de Escharum. A pesar de todo lo que soportó, Esparza resistió lo suficiente para ser rescatado y ahora se encuentra con orgullo junto al Jefe Maestro, ansioso por enfrentar nuevas amenazas y desafíos', 'https://halo.wiki.gallery/images/thumb/d/dd/HINF_Ending_Pilot.png/1600px-HINF_Ending_Pilot.png', 'Figuras notables'),
(7, 'Frederic Ellsworth', 'S-104', 216, '132.00', 'Ballast', 'Teniente, Grado Junior', '2511-04-03', 'Con un repertorio notablemente competente y variado, la habilidad más impresionante de Fred-104 son las tácticas de campo de batalla, lo que le permite operar como líder del Equipo Azul cuando John-117 no está presente. Aunque normalmente mantiene una franqueza informal y seca en la mayoría de sus interacciones, como líder del equipo es austero, clínico y, a menudo, propenso a la reflexión, agobiado por la responsabilidad del rol. A pesar de ello, el verdadero genio de Fred reside en la estrategia, la rápida toma de decisiones y una capacidad natural para forjar elementos de combate dispares en una fuerza de guerra cohesionada, incluso cuando se presentan circunstancias complejas y extremas. Esto se hizo evidente en su liderazgo de los Spartan-III durante el prolongado Conflicto Ónice y una serie de enfrentamientos en la colonia de Gao, pero de manera más significativa cuando lideró valientemente a muchos de los últimos Spartan-II supervivientes en la defensa de Reach.', 'https://www.405th.com/forums/attachments/tumblr_58149278449487af93f91c757f2704ef_0c266155_540-jpg.320744/', 'Equipo azul'),
(8, 'Linda Pravon ', 'S-058', 213, '110.00', 'Verent', 'Suboficial, Primera Clase', '2511-03-19', 'Empleada a menudo como francotiradora exploradora que proporciona apoyo de combate y reconocimiento de largo alcance, las capacidades de Linda-058 son incomparables dentro del programa SPARTAN-II. A pesar de tener un semblante frío y moderado, Linda es extraordinariamente rápida en la evaluación y respuesta estratégica. Su lado independiente y su confianza inquebrantable en su habilidad y entrenamiento significaron que podía ser desplegada eficazmente durante largos períodos de tiempo en misiones de \"lobo solitario\", operando profundamente tras las líneas enemigas. Prefiere una SRS99-S5 modificada, cariñosamente llamada \"Nornfang\", una combinación que la hace prácticamente incomparable en el campo de batalla, y es considerada una de las francotiradoras más talentosas del UNSC. La habilidad de Linda ha demostrado ser invaluable, ya que las directivas de misión a menudo la enfrentan a objetivos de alta prioridad a distancias extremas o le encargan la tarea de proporcionar apoyo de vigilancia a los aliados en condiciones tácticas excepcionalmente desafiantes', 'https://preview.redd.it/spartan-ii-linda-058-in-destiny-2-v0-bxm51touvibb1.jpg?width=640&crop=smart&auto=webp&s=5b9b38475dac6df02d0250fcc3a6c08bb1d10fce', 'Equipo azul'),
(9, 'Kelly Shadoock', 'S-087', 211, '112.00', 'Imber', 'Suboficial, Primera Clase', '2510-09-21', 'Excepcionalmente talentosa tanto en reconocimiento como en combate cuerpo a cuerpo, Kelly-087 poseía reflejos y velocidad notables incluso antes de su aumento biológico y el uso de los sistemas de amplificación Mjolnir. Con su armadura puesta, es capaz de correr a velocidades de aproximadamente 65 km/h durante períodos prolongados, lo que la convierte en una exploradora excepcional y una estratega de ataques relámpago. Aunque cáustica, cínica e incluso insubordinada a veces, la determinación y lealtad de Kelly al Equipo Azul son incuestionables. Está orientada a las tareas y es competitiva, ansiosa por hacer lo que sea necesario para cumplir una misión, incluso a un gran coste para ella misma. Experta en muchas armas, el arsenal preferido de Kelly para combates a corta distancia es siempre la «Oathsworn», una escopeta M45 altamente personalizada con una reputación letal. Las asombrosas habilidades de Kelly exhiben todas las cualidades que han llevado al renombre del Equipo Azul.', 'https://halo.wiki.gallery/images/thumb/9/9c/Enc22-Kelly.png/800px-Enc22-Kelly.png', 'Equipo azul'),
(10, 'Samuel westergaard', 'S-034', 223, '135.00', 'Harvest', 'Suboficial, Segunda Clase', '2511-07-10', 'Un miembro original y fundamental del Equipo Azul, Samuel-034 es un nombre recordado y honrado por todos los Spartans, independientemente de su clase o generación. A pesar de ser el miembro más joven del Equipo Azul, Sam era conocido por su formidable tamaño y fuerza, incluso antes de la mejora. Uno de los compañeros más cercanos de John-117 en el programa SPARTAN-II, el vínculo que forjaron fue el centro de la lealtad y el corazón del Equipo Azul. Cuando los candidatos a Spartan-II fueron enviados a Chi Ceti IV para recuperar la primera línea de armadura Mjolnir, se vieron obligados a abordar una nave de guerra Covenant para evitar un ataque a las instalaciones. Después de sufrir una brecha en su armadura que le impediría salir al espacio, Samuel-034 sacrificaría su propia vida para salvar a su equipo y destruir la nave enemiga. Este valiente acto sirvió para inspirar y galvanizar a sus compañeros Spartans mientras se enfrentaban a la implacable amenaza alienígena durante los treinta años siguientes.', 'https://cdn.personalitylist.com/avatars/434286.png', 'Equipo azul'),
(11, 'Capitán James Cutter', '01730-58392-JC', 185, '88.50', 'Reach', 'Capitán', '2478-05-12', 'James Cutter es un héroe muy estimado de la Armada del UNSC, que sirvió valientemente en el frente durante la insurrección y la Guerra del Covenant\r\n\r\nUn misterio descubierto durante la Batalla de la Cosecha envió al Spirit of Fire lejos del espacio humano. Desde allí, Cutter lideró sin miedo a la tripulación de la nave contra el Covenant, los Desterrados e incluso el Flood, abarcando un enigmático mundo escudo Forerunner y la instalación extragaláctica del Arca. Firmes e inquebrantables, Cutter y lo que queda de las fuerzas del Spirit of Fire.\r\n\r\nhan vuelto a centrar su atención en detener al contingente restante de los Desterrados y encontrar el camino a casa.', 'https://pm1.aminoapps.com/7332/a54716ca136e94bce4509c81384259731aba0b8cr1-1146-816v2_hq.jpg', 'Spirit of fire'),
(12, 'Profesora Ellen Anders', 'CC-500493', 178, '51.70', 'Arcadia', 'Contratista Civíl', '2503-08-13', 'Consultora civil de la ONI con experiencia en ecopoiesiología, exobiología y xenobiología teórica. Ellen Anders desempeñó un papel importante durante las misiones del Spirit of Fire a través de colonias humanas y antiguos mundos Forerunner. La naturaleza impetuosa de la profesora y su fuerte preferencia por la acción y el descubrimiento sobre la precaución contradicen su rico conocimiento y experiencia en investigación, todo lo cual resultó fundamental no solo para proteger a la tripulación del Spirit, sino a toda la humanidad. Durante su batalla contra los Desterrados, Anders logró desplegar una instalación de Halo recién creada desde la fundición del Arca, pero fue detenida por uno de los Guardianes de Cortana cuando intentaba traerla de vuelta al espacio humano.', 'https://production-gameflipusercontent.fingershock.com/us-east-1:900b2748-8a89-4454-a265-010509a4febf/f4e72ff6-ac1f-459e-9412-de7263b9a701/0d4ff714-9209-4c37-9eb8-be06a5e7fd1f', 'Spirit of fire'),
(13, 'Sargento John Forge ', '63492-94758-JF', 191, '97.50', 'Tierra', 'Sargento', '2501-05-29', 'Parte del despliegue de los Marines en el UNSC Spirit of Fire durante su campaña en Harvest, John Forge era conocido principalmente por su pintoresco pasado, su actitud poco profesional y su historial de insubordinación. A pesar de estas facetas negativas, el Capitán Cutter vio el verdadero valor que poseía Forge, principalmente en su coraje puro y su negativa a rendirse sin importar el costo. Con permiso para ejercer una autoridad que excedía su rango formal, Forge lideró desde el frente, inspirando a aquellos a su cargo con coraje sacrificatorio. Su acto final no sería diferente, dando su vida para negar al Covenant el acceso a una flota Forerunner imparable', 'https://pm1.aminoapps.com/6263/a854440a182b1b938634deec128cb6c6ef4f6a37_hq.jpg', 'Spirit of fire'),
(14, 'Jerome Cable', 'S-092', 219, '131.50', 'Minister', 'Comandante (Brevet Comission)', '2511-05-08', 'Nacido del proyecto SPARTAN-II y líder del destacamento del Equipo Rojo que fue recuperado por el Spirit of Fire en Arcadia, Jerome-092 ha luchado junto a Douglas-042 y Alice-130 durante la mayor parte de su carrera. En los primeros cinco años de la guerra, el Equipo Rojo superó a la mayoría de los demás elementos de combate terrestre, mientras se movían de un mundo a otro, intentando detener la amarga masacre del Covenant en las Colonias Exteriores. Después de integrarse con la tripulación del Spirit, Jerome lideró al Equipo Rojo contra las fuerzas del Covenant y de los Desterrados, con el objetivo de evitar que tomaran el control de las poderosas y antiguas armas dejadas por los Forerunners. Mientras la batalla contra los Desterrados continúa rugiendo en la superficie del Arca, la firme determinación y el liderazgo inquebrantable de Jerome se han convertido en la base sobre la que luchan las fuerzas terrestres del Spirit.', 'https://pm1.aminoapps.com/7950/dc295065a44f12579d90da1dd9a121b429e57345r1-426-426v2_hq.jpg', 'Spirit of fire'),
(15, 'Edward Buck ', '92458-37017-EB', 206, '113.00', 'Draco 3', 'Spartan', '2510-08-22', 'Más de un cuarto de siglo en combate en el Cuerpo de Marines. Edward Buck era un veterano ODST con un legado ya impresionante como líder antes de convertirse en un Spartan-IV\r\n\r\nLa valentía contagiosa del sargento de artillería, su lealtad inquebrantable y su liderazgo sacrificado definieron su servicio durante años, contribuyendo a su selección para la operación de la ONI en Nueva Mombasa, un evento crucial que ayudó a concluir la guerra. Buck fue seleccionado personalmente por el Jefe de Estado Mayor de SPARTAN-IV, Jun-A266, para su integración en la floreciente rama, pero cuando la traición obligó a Alpha-Nine a disolverse, fue asignado brevemente al Equipo de Asalto Osiris a bordo de la Infinity. Circunstancias críticas finalmente exigieron la reactivación de su antiguo equipo y pronto se encontró de nuevo al mando de Alpha-Nine.', 'https://preview.redd.it/buck-turned-53-today-v0-3308chrlrzqc1.png?width=640&crop=smart&auto=webp&s=cbb950be0ee36e9ce0fd70f6aa4efc125e027735', 'alpha nueve'),
(16, 'Michael Crespo (Mickey)', '51033-15973-MC', 206, '122.90', 'Luna', 'Spartan', '2530-10-20', 'El exjefe de tripulación del Pelican, Michael Crespo, sirvió como experto en demoliciones de Alpha-Nine en el campo, demostrando su habilidad y lealtad durante varias batallas críticas en los últimos meses de la guerra. Sin embargo, el dilema moral que presentaba luchar contra humanos cambió drásticamente las lealtades de Mickey después de que el conflicto terminara, lo que lo llevó a unirse al Frente Rebelde Unido mientras era un Spartan-IV. Esta traición casi diezmó lo poco que quedaba de Alpha-Nine, obligando a Buck y Romeo a rastrear y arrestar a su propio compañero de equipo. Indultado después de demostrar su lealtad al equipo en una peligrosa operación en Cassidy III, Mickey ha sido reincorporado por completo a Alpha-Nine, aunque el UNSC está monitoreando de cerca su actividad.', 'https://comicvine.gamespot.com/a/uploads/scale_medium/11149/111497199/9472447-enc22_mickey.png', 'alpha nueve '),
(17, 'Kojo Agu (Romeo)', '14606-85099-KA', 213, '125.60', 'Madrigal', 'Spartan', '2524-06-12', 'Un tirador y francotirador altamente hábil, las habilidades de combate de Kojo Agu solo son rivalizadas por su comportamiento contencioso y abrasivo y su encanto irreverente, este último le valió el apodo de \"Romeo\". A pesar de su relación antagónica, Romeo continuó luchando al lado de Buck durante la transición del escuadrón a un equipo de fuego Spartan. La desafiante traición de Mickey reforzó aún más el compromiso de Romeo con Alpha-Nine. El talento de Romeo con el rifle de francotirador resultó particularmente útil durante una serie de ataques contra la red de ejecutores armiger de los Creados, neutralizando el acceso del enemigo a los relés de sensores estratégicos, lo que permitió a la UNSC Infinity monitorear sus movimientos de forma segura.', 'https://comicvine.gamespot.com/a/uploads/scale_medium/11149/111497199/9472427-ovniizumk_95zcy2hbjrxxrhkhtea46f1nsp077plg71mldctoxuaqodim9-v76ml_dvdtchoszx5ww2l5c40dzw8ouvdqtg_c3xv6wbomrmiqtfbrhvtyp0nxykzwk1ldvzjtxi4cmhnxh4g_4opw.png', 'alpha nueve'),
(18, 'Taylor Henry Miles (Dutch)', '21175-12121-TM', 211, '130.20', 'Marte', 'Spartan', '2519-06-03', 'Taylor Miles, quien fuera conductor de tren de carretera en Marte, luchó como ODST junto a Kojo Agu y Gretchen Ketola, su futura esposa, antes de unirse a Alpha-Nine. La fe y el optimismo de Dutch se pusieron a prueba severamente cuando el Novato murió trágicamente, lo que le obligó a abandonar brevemente el Cuerpo. Finalmente, regresó a Alpha-Nine, esta vez junto a su esposa como espartano, más fuerte y con más confianza que nunca. Dutch sigue siendo la roca de su equipo, un soldado compasivo y lúcido cuya habilidad innata en el combate y lealtad inquebrantable nunca deben ser cuestionadas', 'https://comicvine.gamespot.com/a/uploads/scale_medium/11149/111497199/9472402-fwbumifxsau1hks.jfif.jpg', 'alpha nueve'),
(19, 'Gretchen Ketola', '72831-500211-GK', 203, '109.30', 'Harvest', 'Spartan', '2520-05-14', 'Sirviendo con Romeo y Dutch antes de que se unieran a Alpha-Nine, Gretchen Ketola fue una ODST notable conocida por su valentía e incluso su alegría ante la muerte.\r\n\r\nDurante una fatídica operación en Ballast, perdió su pierna izquierda al pisar una mina terrestre insurgente. El trauma físico y psicológico de este evento la llevó a abandonar la Infantería de Marina, incluso si eso significaba estar físicamente lejos de Dutch, con quien se había casado recientemente. Después de la guerra, aceptó una oferta para regresar al combate, con su cuerpo reforjado en el de una Spartan.', 'https://pbs.twimg.com/media/FL_H0W-XMAAy4P2?format=jpg&name=small', 'alpha nueve'),
(20, 'Jonathan Doehrty (El novato)', '11282-31220-JD', 186, '88.00', 'Luna', 'Cabo primero', '2525-02-09', 'El ODST, a menudo llamado el Novato por su escuadrón, se integró en Alpha-Nine justo antes del asedio del Covenant a Nueva Mombasa, donde ayudó a asegurar el activo de Nivel 1 que la ONI buscaba. Permaneció con Alpha-Nine después de la guerra, cuando el equipo fue redesplegado para enfrentarse a una gran cantidad de nuevas amenazas, incluidos los rebeldes en Draco III, donde murió trágicamente mientras luchaba junto a su equipo. Su muerte fue un momento decisivo para el equipo, creando profundas heridas que no sanarían rápidamente.', 'https://comicvine.gamespot.com/a/uploads/scale_medium/11149/111497199/9472449-h3odst-therookie.jpeg', 'alpha nueve'),
(21, 'Veronica Dare', '73998-38490-VD', 170, '69.40', 'Actium', 'Capitana', '2515-12-04', 'Capitana de la Sección Uno de la ONI, Veronica Dare seleccionó originalmente a Alpha-Nine para la operación clasificada en Nueva Mombasa debido a su confianza en la capacidad de Buck para completar la misión, incluso a pesar de las dificultades que sufrieron en su relación. Aunque no es miembro formal, ha estado estrechamente vinculada a Alpha-Nine desde entonces y actualmente se desempeña como analista de campo principal de la ONI en la UNSC Infinity. Los parámetros operativos de Dare fueron en gran medida ilimitados bajo el mando del Capitán Lasky, debido en parte a su coraje inquebrantable y su personalidad implacable', 'https://pm1.aminoapps.com/6432/c877cdf3c992cc5a8d505b95520a7e91655ad998_hq.jpg', 'alpha nueve'),
(22, 'Carter-A259', 'S-A259', 208, '113.40', 'Biko', 'Comandante', '2520-08-27', 'Líder experimentado y curtido en la batalla del Equipo Noble, Carter-A259 refleja lo mejor del programa SPARTAN-III. Años en la sangrienta lucha contra el Covenant han hecho que Carter sea motivado, autoritario y confiado en las capacidades de su equipo. Su precisión férrea y serena oculta una frustración subyacente por la pérdida de comandos que habían servido anteriormente en Noble, como su amigo Thom-A293. Noble Uno había aprendido a lo largo de los años luchando tanto contra las despiadadas fuerzas alienígenas del Covenant como contra grupos atrincherados de rebeldes humanos que el alto precio del liderazgo debe afrontarse con un coraje intrépido y una disciplina inquebrantable. Durante la última incursión de Noble para entregar un activo vital al Pillar of Autumn, Carter sacrificó su vida para ganar tiempo para que su equipo completara su misión.', 'https://i.pinimg.com/1200x/36/0d/fe/360dfefb3d36547901e71c7f5ea9adb1.jpg', 'equipo noble'),
(23, 'Kat-B320', 'S-B320', 206, '97.50', 'New Harmony', 'Teniente Comandante', '2530-01-30', 'Recuperada de la Compañía Beta justo antes de sus catastróficas pérdidas en la Operación TORPEDO, Kat-B320 fue asignada al Equipo Noble y sirvió como segunda al mando hasta el final de la guerra. Su agudo intelecto estratégico y su crudo instinto táctico se vieron aumentados por su especialización en guerra electrónica y comunicaciones, un conjunto de habilidades que la hicieron en gran medida inigualable entre sus compañeros. Aunque a menudo brusca e irreverente con la autoridad, la responsabilidad principal de Kat era analizar datos y planificar los componentes tácticos de las operaciones de Noble, y este fue el principal factor que contribuyó al notable éxito del equipo en el campo. Trágicamente, murió durante la rápida extracción del Equipo Noble de Nueva Alejandría.', 'https://pm1.aminoapps.com/7398/7b38a2951b5d7056623e20ebae915ac40ed84d33r1-600-540v2_hq.jpg', 'equipo noble'),
(24, 'Jun-A266', 'S-A266', 211, '111.10', 'New Harmony', 'Jefe de Staff, Rama Spartan', '2524-02-28', 'Como único miembro superviviente del Equipo Noble, Jun-A266 ahora sirve como Jefe de Estado Mayor de la rama Spartans, bajo la dirección del Comandante en Jefe de Escuadrón Espartano Musa Ghanam, donde ayuda con el análisis, el reclutamiento y el entrenamiento de todos los operativos entrantes del Spartan-IV. Durante su tiempo en Noble, Jun era tranquilo, clínico y pragmático, un operativo solitario que a menudo se desplegaba en solitario para procedimientos discretos de reconocimiento y eliminación de objetivos. Cuando el Equipo Noble fue desplegado en su misión final en Asźod, se vio obligado a separarse y escoltar a la Dra. Catherine Halsey a la base CASTLE. Después de la guerra, se unió a Ghanem en las primeras etapas del Spartan-IV, con la esperanza de que evitara las inmensas bajas sufridas por sus compañeros en el programa Spartan-III. La experiencia de Jun ha contribuido significativamente a su éxito.', 'https://i.pinimg.com/736x/36/da/ee/36daee572f006b97da8bae54be3a7dbe.jpg', 'equipo noble'),
(25, 'Emile-A239', 'S-A239', 205, '106.50', 'Eridanus 2', 'Suboficial', '2523-03-11', 'Un producto poco común de la Compañía Alfa, Emile-A239 no solo era un guerrero notablemente talentoso y un hábil especialista en combate cuerpo a cuerpo, sino que también era implacablemente despiadado y propenso a la exageración, a menudo con la esperanza de quebrar la voluntad del enemigo mediante el uso de fuerza innecesaria. Aunque su tiempo con el Equipo Noble moderó este comportamiento en cierta medida, nunca lo erradicó por completo. Cada soldado Covenant que mataba era un grabado en su visor, que eventualmente formaba un rostro inquietante que esperaba infundiera miedo en los corazones de aquellos a quienes se enfrentaba. Aunque descarado y frívolo en la batalla, fuera del combate, Emile a menudo era frío e insensible, incluso con aquellos de su propio equipo. Sin embargo, sacrificó su vida en su operación final, protegiendo a Noble Seis de un grupo de batalla Covenant que convergente sobre los astilleros de desguace de barcos en Asźod.', 'https://i.pinimg.com/1200x/49/e1/a9/49e1a91e5cb954e78bbcb287d93b4c37.jpg', 'equipo noble'),
(26, 'Jorge-052', 'S-052', 224, '145.20', 'Reach', 'Suboficial Jefe', '2511-03-05', 'El único Spartan-II entre las filas del Equipo Noble, Jorge-052 no solo era un talentoso especialista en armas pesadas, sino también un soldado incondicional y experimentado con décadas de servicio que ayudaron a mitigar el celo algo imprudente del joven equipo en sus primeros años. Si bien su tamaño y fuerza lo convertían en un candidato ideal para el programa SPARTAN-II, el ingenio y la previsión táctica de Jorge eran lo que a menudo le daba una clara ventaja sobre los demás. A medida que la Guerra del Covenant se prolongaba durante décadas, Jorge albergaba en secreto el deseo de morir en medio de la batalla, una actitud que impulsaba maniobras arriesgadas que incluso los soldados experimentados habrían evitado. Su profundo afecto por su mundo natal y su gente finalmente lo llevó a una de esas operaciones, donde Jorge finalmente dio su vida para destruir un superportaaviones Covenant que ocupaba Reach.', 'https://i.pinimg.com/1200x/a2/fd/24/a2fd24e2ad05d4fbeb12b571f334e835.jpg', 'equipo noble'),
(27, 'Noble Seis-B312', 'S-B312', 206, '108.50', '[Clasificado]', 'Teniente', '2530-01-30', 'Cuando Thom-A293 dio su vida para destruir un crucero enemigo en la defensa de Fumirole por parte de Noble, esto dejó una vacante en el equipo que el Coronel Urban Holland estaba ansioso por llenar, especialmente a medida que el Covenant continuaba avanzando hacia los mundos centrales humanos\r\n\r\nA pesar de un historial letal de operaciones como lobo solitario, Spartan-B312 fue finalmente seleccionado para completar el Equipo Noble. Dado el historial de Spartan en antiterrorismo y su eficiencia quirúrgica contra las milicias rebeldes, gran parte del historial de Noble Six ha sido censurado y borrado, incluyendo los detalles de una operación en Mamore donde Spartan-8312 utilizó un caza espacial altamente clasificado para defender la colonia de una insurgencia despiadada. Esta victoria clave, que se debió al asombroso conjunto de habilidades de Six, fue lo que inclinó la balanza, lo que llevó no solo a su colocación en Noble, sino también a una valiente campaña en Reach, que terminó en un sacrificio que conduciría a la victoria de la humanidad', 'https://pm1.aminoapps.com/7156/41001ec3f3139ae5bc454a2a814f0e5192db8e56r1-786-715v2_hq.jpg', 'equipo noble'),
(28, 'Capitán Thomas Lasky', '98604-72690-TL', 182, '76.70', 'Marte', 'Capitán', '2510-08-15', 'Un líder probado y un estratega naval experimentado en batalla, Thomas Lasky sirve como capitán de la UNSC Infinity, un rol al que se vio obligado repentinamente tras los eventos en Requiem. Lasky se sometió a un bautismo de fuego después de soportar un intenso régimen de entrenamiento en la Academia de Ciencias Militares Corbulo y sobrevivir a la invasión Covenant de Circinius IV. Debido a estas experiencias, Lasky mantuvo rigurosamente una carrera estricta y fue considerado un comandante que seguía las reglas, generalmente pecando del lado de la sabiduría convencional. Este enfoque ha sido probado desde entonces en el crisol de múltiples enfrentamientos navales, abordajes enemigos, disensiones entre los suyos e incluso traición, lo que lo obligó a adaptarse, pensar de forma innovadora y tomar riesgos cuando hay mucho en juego.', 'https://i.pinimg.com/736x/e5/90/0c/e5900c1d88d7d44083c673d7f64d701f.jpg', 'unsc infinity'),
(29, 'Sarah Palmer', '65287-98303-SP', 206, '109.30', 'Luna', 'Comandante Spartan', '2527-04-13', 'Como comandante de todas las fuerzas Spartan a bordo del UNSC Infinity, Sarah Palmer conoce muy bien el alto costo del liderazgo gracias al sacrificio de los muchos Spartans que han luchado bajo su mando. Sirviendo en el Cuerpo de Marines durante la guerra, Palmer participó en doce períodos completos de servicio en ocho colonias diferentes, repeliendo las invasiones del Covenant una y otra vez, hasta que fue reclutada en el programa militar clasificado SPARTAN-IV. Una de las primeras en ser desplegadas como la rama militar más nueva de la humanidad de guerreros aumentados, Palmer se vio envuelta en una miríada de conflictos de posguerra enconados y finalmente recibió el mando de los Spartans de la Infinity, donde ha luchado codo con codo con aquellos a su cargo para prevenir innumerables amenazas en mundos alienígenas.', 'https://i.pinimg.com/736x/b0/42/43/b04243a4e22a9172bd2b90735af770c6.jpg', 'unsc infinity'),
(30, 'Jameson Locke', '73808-03153-JL', 208, '116.00', 'Jericho 7', 'Spartan', '2529-03-15', 'Como estratega de combate experimentado y brillante investigador criminal, en muchos sentidos, Jameson Locke representa la cúspide de la próxima generación de soldados de la humanidad. Su nombramiento como líder del altamente cualificado Equipo de Fuego Osiris era obvio, ya que había liderado con maestría un equipo de investigación de élite de la ONI durante años, eliminando silenciosamente varias de las mayores amenazas de la humanidad que acechaban en las sombras. Sin embargo, los talentos únicos de Locke y su inigualable experiencia en rastreo se pusieron a prueba en 2558, cuando Osiris fue enviado a cazar al legendario Jefe Maestro. Esta fatídica operación condujo a la revelación de una IA inconformista que intentaba consolidar un poder que abarcaba toda la galaxia a través de la tecnología Forerunner.', 'https://i.pinimg.com/736x/c2/7e/02/c27e02a0b66362c791014049b064d8c5.jpg', 'unsc infinity'),
(31, 'Holly Tanaka', '93312', 201, '108.40', 'Minab', 'Spartan', '2530-07-09', 'Holly Tanaka, una superviviente curtida en la batalla y una soldado excepcionalmente talentosa, representa la mente de ingeniería y electrónica del Equipo de Fuego Osiris, completando el conjunto de habilidades de la unidad con una capacidad natural para descifrar y utilizar una gama de tecnologías, independientemente de la especie de origen y sin la ayuda de una IA proxy. Entrenada en infiltración de sistemas y subversión durante su tiempo en el Ejército, Tanaka agudizó una habilidad innata para la ingeniería inversa de casi cualquier cosa. De niña, sobrevivió por poco a una serie traumática de eventos durante la brutal destrucción de Minab, incorporando coraje, resiliencia e ingenio a su carácter, así como una reticencia a confiar en los demás. Como parte del Equipo de Fuego Osiris, Tanaka se vio obligada a desprenderse de sus inclinaciones tranquilas y autosuficientes, y aprendió a poner su vida en manos de sus compañeros de equipo.', 'https://i.pinimg.com/1200x/1e/1e/d8/1e1ed8b64549feecd715b3863463c15d.jpg', 'unsc infinity'),
(32, 'Olympia Vale', '44482-91201-OV', 206, '101.60', 'Luyten', 'Spartan', '2536-01-20', 'La antropóloga de campo y experta Sangheili del Equipo de Asalto Osiris, Olympia Vale, es el producto de años de experiencia de posguerra inmersa en la cultura del antiguo enemigo de la humanidad: los Élites. Sirviendo como enlace diplomático formal con el pueblo Sangheili, lideró a la humanidad en sus esfuerzos por formar una fuerte alianza con las Espadas de Sanghelios, desarrollando un conocimiento magistral de su especie y moldeando definitivamente su papel como Spartan en los años venideros. En los eventos que llevaron al ascenso de Cortana al poder, Vale fue fundamental en la construcción de una coalición entre la humanidad y las fuerzas del Árbitro. Con los brutales esfuerzos de los Desterrados por apoderarse de Zeta Halo y usarlo contra sus enemigos, ahora más que nunca se necesitan lazos tan profundos entre aliados, no solo por el bien de la humanidad, sino por el de todos los que se encuentran al alcance de Atriox.', 'https://i.pinimg.com/736x/a5/d1/65/a5d1655bc81ed967fa738eaa2a8666ef.jpg', 'unsc infinity'),
(33, 'Gabriel Throne ', '83920-91083-GT', 208, '101.60', 'Tierra', 'Spartan ', '2534-07-05', 'Proveniente de una larga tradición familiar de servicio militar, Gabriel Thorne ahora sirve como líder del Equipo de Asalto Majestic, un elemento Spartan clave a bordo del UNSC Infinity. Como parte del Ejército, Thorne jugó un papel importante en la defensa de Marte en los últimos días de la guerra. Durante su proceso de reclutamiento en la rama Spartan, su familia se perdió en el devastador asalto a Nueva Fénix, lo que alimentó su deseo de luchar contra los enemigos de la Tierra. En su primera campaña a bordo del Infinity, Thorne fue asignado al Equipo de Asalto Majestic y ayudó en batallas críticas, forzando al Covenant de Jul \'Mdama a retroceder para evitar que tomara el control de Requiem. Después de una serie de acciones heroicas en los breves conflictos que siguieron, a Thorne se le otorgó el puesto de líder del equipo Majestic, un papel que ha desempeñado valientemente desde entonces.', 'https://i.pinimg.com/736x/31/16/2c/31162cdefe8f0e4771c4e5d451ee68c0.jpg', 'unsc infinity'),
(34, 'Hudson Griffin', '[Desconocido]', 208, '120.00', 'Lodestone', 'Spartan', '2530-11-14', 'Hudson Griffin era un soldado condecorado y un candidato ideal para el programa SPARTAN-IV. Como líder del Equipo de Asalto Taurus, Griffin ayudó al Equipo Azul durante un conflicto en Reach a finales de 2559, ayudando a las fuerzas coloniales locales contra la ocupación de los Desterrados. Poco después, Griffin acudió en ayuda del Jefe Maestro una vez más, esta vez ayudando en la evacuación segura del Capitán Lasky durante el asalto de los Desterrados a la UNSC Infinity en Zeta Halo. Griffin ayudó a liderar una resistencia humana en la superficie del anillo, pero tras un fallido intento de asesinato contra el jefe de guerra de los Desterrados Escharum, fue capturado, retenido e interrogado por el señor de la guerra Chak \'Lok. A pesar de la intervención del Jefe Maestro, Griffin sucumbió a sus heridas, no sin antes transmitirle información vital que ayudó enormemente al Jefe y a los esfuerzos de la humanidad en el anillo.', 'https://halo.wiki.gallery/images/6/67/Enc22-Griffin.png', 'heroeszetahalo'),
(35, 'Vedrana Makovich', '[Desconocido]', 206, '109.00', 'Andesia', 'Spartan', '2531-04-09', 'La líder del Equipo de Asalto Windfall, Vedrana Makovich, se hizo un nombre en la Fuerza Aérea del UNSC como una de sus pilotos más versátiles y hábiles. Después de auspiciosos períodos volando una amplia gama de cazas, Makovich fue invitada al programa SPARTAN-IV, donde, además de liderar una impresionante lista de salidas exitosas contra grupos de asalto enemigos, también jugó un papel decisivo en el desarrollo del modelo de producción Sabre. A finales de 2559, Makovich formó parte del contingente del UNSC que asaltó Zeta Halo. Después de ser emboscada por las fuerzas de los Desterrados, jugó un papel vital en la resistencia humana. Finalmente, murió en batalla meses después mientras intentaba evitar que el enemigo localizara el monitor de la instalación.', 'https://halo.wiki.gallery/images/6/63/Enc22-Makovich.png', 'heroeszetahalo'),
(36, 'Bonita Stone', '[Desconocido]', 208, '110.00', 'Komoya', 'Spartan ', '2535-12-25', 'Antes de su incorporación al programa SPARTAN-IV, Bonita Stone sirvió con distinción en el crucero furtivo Relentless Watch del UNSC, donde coordinó los esfuerzos de varios equipos de reconocimiento desplegados en áreas clave de interés y disturbios tras la Guerra del Covenant. Esta experiencia la llevó directamente a su asignación al Equipo de Asalto Shadow después de su aumento. En 2560, Stone formó parte del grupo Spartan-IV a bordo del UNSC Infinity durante su fatídica misión a Zeta Halo. Durante una angustiosa operación de reconocimiento dentro de la subestructura de la instalación, Stone inspeccionó a las fuerzas desterradas mientras desenterraban un cilix Forerunner, un dispositivo de contención que contenía una amenaza que el UNSC aún no había detectado. Finalmente, Stone murió en batalla tras los esfuerzos por advertir a otros de los peligros potenciales que la intromisión de los Desterrados podría desatar.', 'https://haloprojectbrasil.com.br/wp-content/uploads/2023/07/bonita-stone-halo_1.webp', 'heroeszetahalo'),
(37, 'Nina Kovan', '[Desconocido]', 206, '108.00', 'Gilgamesh', 'Spartan', '2534-03-21', 'Durante toda su carrera, Nina Kovan fue considerada una tiradora ejemplar. Eventualmente.\r\n\r\nCuando el conocimiento de las heroicas hazañas de los súper soldados Spartan como Linda-058 comenzó a ser más conocido, Kovan se obsesionó con el estudio de los registros y métodos Spartan, con la esperanza de aprender cualquier cosa que pudiera aplicar a su propio enfoque en el campo de batalla. Cuando se le ofreció la oportunidad de convertirse en Spartan, Kovan la aprovechó, ansiosa por seguir los pasos de sus héroes. Durante la emboscada de los Desterrados a las fuerzas del UNSC en Zeta Halo en 2560, Kovan luchó valientemente contra las fuerzas Desterradas, defendiendo una fortaleza humana en el lugar donde se encontraba la fragata derribada Mortal Reverie', 'https://halo.wiki.gallery/images/6/66/Enc22-Kovan.png', 'heroeszetahalo'),
(38, 'Theodoore Sorel', '[Desconocido]', 211, '122.00', 'Forseti', 'Spartan', '2527-08-02', 'Criado en Forseti, Theodore Sorel estuvo en gran medida aislado de los horrores de la guerra, destacando en cambio en la música en su juventud. A medida que sus primeros éxitos comenzaron a exponerlo a un público más amplio, y a las realidades a las que se enfrentaban la mayoría de los demás ciudadanos de la UEG, Sorel decidió cambiar por completo el curso de su vida. Una exitosa carrera militar culminó con una invitación al programa SPARTAN-IV. Durante los esfuerzos de resistencia del UNSC contra la ocupación de los Desterrados de Zeta Halo, Sorel viajó junto a su compañera Spartan Vedrana Makovich a las instalaciones Forerunner conocidas como el Conservatorio, pero murió al intentar evitar que las fuerzas enemigas localizaran el monitor de la instalación.', 'https://halo.wiki.gallery/images/4/41/Enc22-Sorel.png', 'heroeszetahalo'),
(39, 'Tomas Horvath', '[Desconocido]', 221, '133.00', 'Alluvion', 'Spartan', '2527-02-03', 'Nacido en Alluvion, Tomas Horvath huyó con su familia cuando el Covenant asedió el vibrante mundo. Horvath se alistó en la UNSC y finalmente fue aceptado en las filas de la ODST. Sin embargo, un fallo de equipo en su primer salto en vivo lo dejó con la columna vertebral destrozada, pero con una determinación aún más fuerte. Después de intensos programas de fisioterapia, Horvath vio la rama Spartan como una oportunidad para renacer, aprovechando el extenso conjunto de aumentos del programa para convertirse en más de lo que jamás soñó. Horvath pasó a servir como parte del Equipo de Fuego Intrepid, ayudando a las fuerzas locales en la superficie de Reach antes de unirse a la posterior misión de la UNSC a Zeta Halo.', 'https://halo.wiki.gallery/images/b/ba/Enc22-Horvath.png', 'heroeszetahalo'),
(40, 'Bertold Vettel', '[Desconocido]', 208, '123.00', 'Tierra', 'Spartan', '2532-09-14', 'Aunque Bertold Vettel consideraba que su relación con sus compañeros de escuadrón era increíblemente estrecha, ni siquiera los Spartans Griffin, Dimka u Oshiro sabían mucho sobre su pasado. Como Equipo de Asalto Taurus, el cuarteto se hizo muy conocido dentro de la rama Spartan por su implacable eficiencia, obteniendo varias victorias cruciales contra las fuerzas remanentes del Covenant después de la guerra. Cuando los Desterrados tendieron una emboscada a las fuerzas del UNSC en Zeta Halo a finales de 2559, Taurus perdió a su líder, lo que provocó que Vettel se concentrara inmediatamente en rastrear la ubicación de Griffin con la esperanza de llegar a tiempo para el rescate', 'https://halo.wiki.gallery/images/a/a0/Enc22-Vettel.png', 'heroeszetahalo'),
(41, 'Terrence Hood', '07960-48392-TH', 193, '96.60', 'Tierra', 'Almirante de Flota', '2490-09-04', 'Pocos en las altas esferas del UNSC son tan respetados y distinguidos como el Almirante de Flota Terrence Hood. Como veterano de numerosas campañas militares, Hood ganó un renombre significativo hacia el final de la Guerra del Covenant, cuando dirigió personalmente a las fuerzas restantes del UNSC en defensa de la Tierra y negoció la paz con el Árbitro. Aunque actualmente se desempeña como presidente del Consejo de Seguridad del UNSC, fue llevado al Mundo de Rossbach con Serin Osman, en un esfuerzo por escapar de la violenta consolidación del poder de Cortana en Sydney cuando atacó la sede del gobierno de la Tierra. La sabiduría y el coraje probados en batalla de Hood son necesarios para la humanidad ahora más que nunca.', 'https://halo.wiki.gallery/images/thumb/8/8d/Fleet_Battle_Hood.jpg/400px-Fleet_Battle_Hood.jpg', 'personal naval'),
(42, 'Margaret Parangosky', '00230-00923-MP', 160, '49.00', 'Luna', 'Almirante (Retirada)', '2461-02-21', 'Anteriormente Comandante en Jefe de la Oficina de Inteligencia Naval (CINCONI), Margaret Parangosky era capaz de imponer respeto y temor incluso a los miembros más influyentes de la sociedad civil, militar y criminal. A pesar de su edad y aparente fragilidad, la voluntad de hierro de Parangosky, su personalidad feroz y su capacidad casi sobrenatural para evaluar y manipular a los demás la convertían en una fuerza a tener en cuenta. A pesar de ser fundamental en la aprobación de SPARTAN-II, alberga una profunda desconfianza y odio hacia Catherine Halsey, aunque admite a regañadientes que las acciones de la científica salvaron a la especie humana. Parangosky finalmente nombró a Serin Osman, a quien había preparado personalmente, como su reemplazo.', 'https://halo.wiki.gallery/images/thumb/3/30/Enc22_Parangosky.jpg/400px-Enc22_Parangosky.jpg', 'personal naval'),
(43, 'Serin Osman', '39489-72738-SO', 191, '86.70', 'Cascade', 'Almirante', '2511-04-15', 'Solemne, pragmática y ferozmente leal a sus seres más cercanos, Serin Osman fue una de las candidatas originales a SPARTAN-II, pero falló el proceso de aumento. Fue tomada en secreto bajo el ala de Margaret Parangosky, donde aprendió la cruda necesidad de las decisiones difíciles y el sacrificio. En 2553, fue puesta al mando de su propio equipo de merodeadores y operaciones especiales, Kilo-Five, para desestabilizar a los enemigos del UNSC. En 2555, asumió el papel de su predecesora: CINCONI. Durante el asalto de Cortana a Sydney, Osman fue llevada al secreto e inexplorado Mundo de Rossbach por su IA personal y amiga íntima, Black-Box', 'https://halo.wiki.gallery/images/b/b6/Osmanheader.png', 'personal naval'),
(44, 'Danforth Whitcomb', '11113-32871-DW', 186, '117.00', 'Tierra', 'Vice Almirante', '2489-07-03', 'Inquebrantable y valiente, la férrea compostura de Danforth Whitcomb frente a probabilidades imposibles solo era igualada por la resiliencia de sus convicciones. Cuando el Covenant descendió sobre Reach, Whitcomb armó una bomba NOVA, permitiendo al enemigo llevarla a la Exaltación Gozosa, donde detonaría y mataría a innumerables soldados Covenant, allanando el camino para la fractura del imperio. Whitcomb finalmente dio su vida al liderar una enorme flota Covenant hacia el comprometido Hierofante Inquebrantable, donde la autodestrucción de la instalación engulliría cientos de naves de guerra enemigas que se dirigían a la Tierra. Tal tenacidad implacable frente a una muerte segura definió a los héroes más grandes de la humanidad, y Whitcomb la personificó hasta el final, contribuyendo a más pérdidas Covenant que cualquier otro soldado en la guerra.', 'https://halo.wiki.gallery/images/thumb/b/b7/Enc22_Whitcomb.png/800px-Enc22_Whitcomb.png', 'personal naval'),
(45, 'Hieronymus Stanforth', '00834-19223-HS', 178, '79.40', 'Tierra', 'Vice Almirante', '2486-07-03', 'En gran parte responsable del puesto de Catherine Halsey dentro de la ONI y del programa SPARTAN-II que le siguió, el vicealmirante Stanforth recibió el mando total de todas las operaciones de campo de los Spartan durante los primeros días de la Guerra del Covenant. Cuando la crisis comenzó a llegar a un punto crítico, regresó al mando de la flota y se mantuvo tan impávido y resuelto como en su juventud. Lideró desde el frente en numerosas batallas, incluyendo conflictos cruciales en Sigma Octanus IV, donde logró guiar al UNSC a una rara victoria naval. Sin embargo, en Reach sufrió una trágica derrota que le costó la vida a bordo del UNSC Leviathan\r\n\r\nEl coraje férreo y las tácticas imaginativas de Stanforth se han convertido en un punto de seria reflexión para muchos comandantes navales, incluso tras la Guerra del Covenant, ya que la urgente necesidad de tales cualidades no ha disminuido.', 'https://halo.wiki.gallery/images/thumb/8/8b/Enc22_Stanforth.jpg/400px-Enc22_Stanforth.jpg', 'personal naval'),
(46, 'Preston Cole', '03956-26127-PC', 180, '86.20', 'Tierra', 'Vice Almirante', '2470-11-03', 'Una leyenda en el UNSC, Preston Cole es ampliamente considerado el mejor estratega naval de la era moderna. Su genio táctico y su impresionante historial lo llevaron a un ascenso meteórico, incluso si se vio empañado por su relación ilícita con un comandante rebelde. Sacado de su retiro por el ataque del Covenant a Harvest, Cole finalmente se convirtió en el único comandante de toda la flota expedicionaria del UNSC y promulgó lo que se conoció como el Protocolo Cole, un esfuerzo desesperado por evitar que el Covenant descubriera la ubicación de la Tierra. Se cree que pereció a bordo del UNSC Everest, en una victoria pírrica contra toda una flota del Covenant cerca de Viperidae. El estatus casi mítico de Cole y sus acciones decisivas dentro del UNSC, aunque a menudo fueron foco de análisis y críticas cínicos, sin duda resultaron en que se salvaran miles de millones de vidas.', 'https://halo.wiki.gallery/images/thumb/0/09/Enc22_ColeFull.jpg/800px-Enc22_ColeFull.jpg', 'personal naval');
INSERT INTO `personajes` (`id`, `nombre`, `numero_servicio`, `altura`, `peso`, `mundo_nacimiento`, `rango`, `fecha_nacimiento`, `descripcion`, `imagen`, `categoria`) VALUES
(47, 'Franklin Mendez', '22926-11908-FM', 188, '93.00', 'Sigma Octanus 4', 'Suboficial Mayor', '2492-03-21', 'Un guerrero experimentado que sirvió con valor y distinción en la Armada del UNSC durante décadas, el impacto de Franklin Méndez en la preservación de la humanidad en el siglo XXVI es incalculable. Fuerte, disciplinado y apasionado por inculcar la resiliencia de las generaciones anteriores en los soldados de hoy. Méndez tuvo una carrera excepcional en el frente tanto de la Insurrección como de la Guerra del Covenant, acumulando múltiples Estrellas de Bronce, Plata y Oro, tres Corazones Púrpura por su valor extraordinario y sacrificado, y la Legión de Honor del UNSC. Sin embargo, su papel más importante fue como instructor de instrucción y mentor de los programas SPARTAN-II y SPARTAN-III. Actualmente se desempeña como Director de Seguridad del Proyecto de Investigación Unida Ónix en el masivo y enigmático mundo escudo.', 'https://halo.wiki.gallery/images/thumb/6/65/Enc22_Mendez.jpg/800px-Enc22_Mendez.jpg', 'spartans3'),
(48, 'Lucy Williams', 'S-B091', 160, '80.30', 'Kholo', 'Spartan', '2533-01-28', 'Diseñada para negarle al Covenant una refinería crítica en Pegasi Delta, los arquitectos de TORPEDO sabían que la misión se cobraría la vida de muchos de sus trescientos operadores. A pesar de su diminuto tamaño, Lucy-B091 fue una de las dos únicas Spartan-Ill que sobrevivieron, un hecho que la dejó con un caso severo de trastorno de estrés postraumático (TEPT), dejándola completamente muda durante años. Este hecho le permitió a Kurt Ambrose retirarla del combate y emplearla en el entrenamiento de la Compañía Gamma. No fue hasta sus interacciones con un Huragok llamado Propensa a la Deriva, enterrado en el oscuro interior de Onyx, que finalmente volvió a hablar\r\n\r\nAhora funciona como una parte clave de los esfuerzos de seguridad del Director Méndez en el mundo escudo.', 'https://halo.wiki.gallery/images/thumb/0/05/Enc22_LucyB091_NoHelmet.jpg/800px-Enc22_LucyB091_NoHelmet.jpg', 'spartans3'),
(49, 'Thomas Jiangsu', 'S-B292', 206, '120.20', 'Amadora', 'Spartan ', '2533-04-14', 'Tom-B292 es un Spartan-III reflexivo y pragmático, firmemente leal tanto a sus camaradas como al objetivo del UNSC de proteger a la humanidad. A través de varios desafíos, Tom aprendió a adaptarse, ya que se vio obligado a aceptar rápidamente la pérdida de sus padres y los sacrificios hechos por sus compañeros Spartan-III durante la devastadora Operación: TORPEDO. Sin embargo, aún conserva un fuerte sentido del deber mezclado con la aprensión de no estar haciendo justicia a sus recuerdos. Después de llevar a cabo una serie de ataques clave contra el Covenant como supersoldado Spartan-III, Tom ayudó con el entrenamiento de la Compañía Gamma, para luego ser reclutado por la rama Spartan y, finalmente, por la fuerza de seguridad del UNSC presente en Onyx.', 'https://halo.wiki.gallery/images/thumb/a/a2/Enc22_TomB292.jpg/800px-Enc22_TomB292.jpg', 'spartans3'),
(50, 'Kurt Ambrose', '045888947', 231, '162.40', 'Circumastance', 'Teniente Comandante ', '2511-10-19', 'Desde los primeros días de su entrenamiento como SPARTAN-II, Kurt-051 fue visto por sus superiores como un líder talentoso y un estratega excepcional. En 2531, la ONI lo envió para investigar una posible actividad rebelde en la desmantelada Estación Delphi, pero esto resultó ser una artimaña para reclutarlo en secreto para liderar el proyecto SPARTAN-III desde el mundo clasificado de Onyx, donde se le dio el nuevo apellido \"Ambrose\" para ocultar su identidad: Trabajando en estrecha colaboración con Franklin Méndez, Kurt dedicó su vida a entrenar a varias compañías de Spartan-III, formadas por niños voluntarios que quedaron huérfanos por la campaña genocida del Covenant Durante ese tiempo, aprendió la pesada responsabilidad de ver a los jóvenes soldados que criaba ser utilizados cruelmente como piezas de juego en un esfuerzo por ganar más tiempo para la humanidad, y a menudo buscaba maneras de mitigar la aparentemente innecesaria pérdida de vidas. En 2552, Kurt-051 dio su vida para brindarles a sus seres queridos la oportunidad de escapar de una vasta fuerza invasora del Covenant, decidida a saquear el mundo escudo', 'https://halo.wiki.gallery/images/b/b9/Enc22_Kurt.png', 'spartans3'),
(51, 'Owen Uduike', 'S-B096', 203, '107.50', 'Eremus', 'Spartan', '2530-04-12', 'Un soldado excepcional, con una tenacidad notable y una concentración absoluta, Owen-B096 se abrió camino a través del agotador entrenamiento y aumento del programa SPARTAN-III para obtener los máximos honores, lo que finalmente lo sacó a él y a otros del despliegue estándar de la Compañía Beta y los llevó a operaciones especializadas. Como parte de Anchor, un equipo de ataque Spartan-III, Owen fue desplegado por la ONI en varios mundos en un esfuerzo por frenar el asalto de una tenaz flota Covenant. Separado de su equipo durante la operación en Meridian, demostró su habilidad innata para entrenar y educar a otros al preparar con éxito a un puñado de adolescentes civiles en la defensa de su mundo natal. Antes de ser asignado para enfrentarse a la creciente amenaza de los Desterrados, Owen fue emparejado con su compañera Spartan Hazel-A302 y sirvió en un programa de educación civil llamado Descubrimiento de Puestos de Avanzada.', 'https://halo.wiki.gallery/images/thumb/1/1b/Enc22_OwenB096.jpg/800px-Enc22_OwenB096.jpg', 'spartans3'),
(52, 'Hazel Leonidov', 'S-A302', 191, '103.90', 'Alluvion', 'Spartan', '2521-01-31', 'Incluso antes de ofrecerse como voluntaria para SPARTAN-III, Hazel-A302 ya era una atleta extraordinaria con una mente brillante. Esta impresionante habilidad se ejemplificó en su entrenamiento dentro de la Compañía Alfa, lo que llevó a la ONI a aprovechar sus habilidades en su naciente programa HEADHUNTER\r\n\r\nFue aquí donde funcionó principalmente como una agente solitaria, llevando a cabo operaciones de reconocimiento a largo plazo, eliminando discretamente objetivos de alto valor y negando al enemigo los activos críticos del UNSC. Durante años, Hazel se dedicó a esta tarea con poca supervisión, rastreando y eliminando implacablemente a figuras clave dentro de los campamentos enemigos. Recientemente, se unió a Owen-8096, proporcionando seguridad para el Puesto de Avanzada Discovery antes de ser redesplegada.\r\n\r\nSu nueva misión sería evitar que los Desterrados saquearan las cadenas de suministro que conectaban las colonias en la periferia. Con la ocupación de Zeta Halo por parte de los Desterrados, socavar los recursos del enemigo no podría ser más crítico.', 'https://halo.wiki.gallery/images/thumb/d/d5/Enc22_HazelA302.jpg/800px-Enc22_HazelA302.jpg', 'spartans3'),
(53, 'Ashley Gable', 'S-G099', 195, '95.00', 'Alluvion', 'Suboficial, Primera Clase', '2539-03-05', 'Especialista en vigilancia y reconocimiento de los Hurones de la ONI, Ash-G099 fue anteriormente el líder del Equipo Sable de SPARTAN-III durante el ejercicio de máximos honores de la Compañía Gamma, un aspecto de su pasado que continuamente influye en su función actual. A pesar de su corta edad, la sabiduría estratégica de Ash y su habilidad para rastrear objetivos son indispensables, especialmente dada la tarea principal de los Hurones de encontrar, detener e incluso eliminar amenazas a la humanidad, independientemente de su origen. Sin embargo, la operación más reciente de los Hurones en el Arca lo ha afectado dramáticamente de maneras imprevistas. La reciente pérdida de Mark sigue siendo un desafío para Ash, quien sentía una profunda obligación hacia su compañero de equipo y, aunque injustificada, asume la responsabilidad de la muerte de Mark', 'https://halo.wiki.gallery/images/f/f9/Enc22-Ash.png', 'operadores especiales'),
(54, 'Olivia Tut', 'S-G291', 188, '78.00', 'Miridem', 'Teniente, Grado Junior', '2538-09-26', 'Olivia-G291, parte instrumental del Equipo Saber de la Compañía Gamma, fue una de las pocas supervivientes que escaparon del violento desmantelamiento de Onyx y entraron en el mundo escudo oculto en su interior. Tras una breve temporada con el legendario Equipo Azul, Olivia y el resto de Saber fueron reasignados como parte de los Hurones, un equipo ideado por Serin Osman para erradicar a los enemigos más atrincherados del UNSC. Dada su propensión a la intrusión de software y al análisis de datos, el papel de Olivia en los Hurones como especialista en información y comunicaciones fue una elección natural. Al igual que los demás miembros de su equipo, todavía está lidiando con la trágica e inesperada muerte de Mark en el Arca.', 'https://halo.wiki.gallery/images/thumb/2/21/Enc22_OliviaG291.jpg/300px-Enc22_OliviaG291.jpg', 'operadores especiales'),
(55, 'Mark Han', 'S-G313', 193, '92.00', 'Veltun', 'Suboficial, Primera clase', '2538-12-23', 'A pesar de las limitaciones inherentes a todos los Gammas, dadas las modificaciones genéticas realizadas a su compañía, la capacidad innata de Mark-G313 para procesar y evaluar amenazas bajo un estrés extraordinario era asombrosa, ya sea durante su tiempo en el Equipo Saber o en su puesto más reciente, como especialista en seguridad en los Hurones. Despiadadamente protector de sus seres queridos y ferozmente testarudo cuando le apetecía serlo, Mark a menudo se encontraba en el centro de la controversia, un lugar en el que se siente más que cómodo. Este hecho se hizo vívidamente evidente en el Arca, cuando, después de llevar su cuerpo mucho más allá de cualquier limitación racional, Mark continuó luchando para proteger las vidas de sus compañeros de equipo, acciones que finalmente resultaron en su muerte a manos del Prelado Dhas Bhasvod.', 'https://halo.wiki.gallery/images/thumb/d/dc/Enc22_MarkG313.jpg/800px-Enc22_MarkG313.jpg', 'operadores especiales'),
(56, 'Veta Lopis', '93553-24752-VL', 177, '65.00', 'Gao', 'Suboficial, Segunda clase', '2520-05-07', 'Anteriormente inspectora especial del Ministerio de Protección de Gao, pero cuando la corrupción en el gobierno de su mundo natal la convirtió en fugitiva, Veta Lopis aceptó a regañadientes un puesto en la ONI como investigadora criminal principal del equipo Hurón. También se convirtió, sin saberlo, en la madre involuntaria de tres irreverentes pero altamente hábiles Spartan-III: Ash-G099, Olivia-G291 y Mark-G313 El cinismo de Lopis, intensificado por años de resolver los casos más complejos de Gao, le ha otorgado un eminente sentido de la justicia, incluso si requiere acciones no autorizadas y mortales de su parte. El trabajo más reciente de los Hurones los vinculaba invariablemente con Castor y los Guardianes de la Libertad Única, lo que los obligaba a actuar de forma encubierta como fanáticos serviles, una operación que exigía todas las habilidades que Lopis había adquirido a lo largo de los años. Esta misión culminó con un esfuerzo por evitar la activación de Halo en el Arca, cuyo amargo precio sería la impactante pérdida de su compañero de equipo, Mark.', 'https://halo.wiki.gallery/images/thumb/5/5f/Enc22_VetaLopis.jpg/800px-Enc22_VetaLopis.jpg', 'operadores especiales'),
(57, 'Rion Forge', '[Ninguno]', 178, '52.60', 'Tierra', 'Civil', '2524-09-18', 'Una rescatadora experta e ingeniosa, la inclinación de Rion Forge por encontrar lo valioso entre los desechos no solo le sirvió como una habilidad útil en su oficio, sino como un tema subyacente en sus esfuerzos más personales. La confiada y audaz capitana de una nave clase Mariner, Ace of Spades, tenía como verdadero objetivo encontrar algo mucho más valioso para ella que cualquier resto de alta tecnología: buscaba la verdad sobre la desaparición de su padre, el sargento John Forge, quien se había desvanecido junto con el resto de sus compañeros de tripulación a bordo del UNSC Spirit of Fire. Finalmente, Rion descubrió la verdad sobre el sacrificio de su padre, pero para su sorpresa, solo marcaría el comienzo del verdadero viaje de su vida.', 'https://halo.wiki.gallery/images/thumb/4/42/Enc22_Rion.png/300px-Enc22_Rion.png', 'salvadores'),
(58, 'Spark', '[Ninguno]', 300, '196.90', 'Geranos-a', 'Ninguno', '0000-00-00', 'Hace más de cien milenios, un simple humano llamado Chakas se encontró desempeñando un papel inesperadamente crucial en el punto crucial de la peligrosa unión de la humanidad con los Forerunner y el Flood. Con el tiempo, se convertiría en 343 Guilty Spark, sirviendo como monitor de Alpha Halo, vigilando la instalación hasta su fatídica destrucción a manos del Jefe Maestro en 2552. Durante el conflicto que siguió, su caparazón de monitor fue destruido, pero la ONI recuperó elementos centrales de su matriz de personalidad y los analizó a bordo del UNSC Rubicon. Incapaz de ser contenido, Guilty Spark logró apoderarse de la nave y escapar, implantando su esencia en el chasis de un armiger Forerunner. Finalmente, este armiger fue descubierto por Rion Forge y el As de Picas, lo que llevó a que el constructo, ahora conocido simplemente como «Spark», se convirtiera en parte de la tripulación de la nave A bordo del As de Picas, Spark se embarcó en un viaje de expiación y auto-redescubrimiento, reuniéndose con el propósito que el Bibliotecario tenía para él desde hacía mucho tiempo y, finalmente, tomando el lugar que le correspondía como cuidador de Bastión, un mundo escudo secreto Forerunner que contenía los secretos, experimentos y revelaciones mejor guardados de la Bibliotecaria.', 'https://halo.wiki.gallery/images/9/9d/Spark_Armiger.jpg', 'salvadores');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `personajescomunidad`
--

CREATE TABLE `personajescomunidad` (
  `id_personaje` int(11) NOT NULL,
  `nombre` varchar(100) NOT NULL,
  `descripcion` text NOT NULL,
  `imagen_url` text NOT NULL,
  `id_usuario` int(11) NOT NULL,
  `fecha_creacion` datetime DEFAULT current_timestamp()
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Volcado de datos para la tabla `personajescomunidad`
--

INSERT INTO `personajescomunidad` (`id_personaje`, `nombre`, `descripcion`, `imagen_url`, `id_usuario`, `fecha_creacion`) VALUES
(6, 'Mariam Keyes', 'Participo en la defensa de Reach durante el ataque del covenant ', 'imagenes_personajes/1000155074.png', 15, '2025-08-04 07:46:00'),
(13, 'Dr. Cervan L. Homer', 'El Dr. Cervan L. Homer comenzÃ³ su carrera en la UNSC como un talentoso cientÃ­fico e ingeniero, destacÃ¡ndose rÃ¡pidamente por su trabajo en el desarrollo de la armadura Mjolnir, la icÃ³nica protecciÃ³n utilizada por los Spartans-II. Su enfoque en mejorar los sistemas de soporte vital, interfaces neuronales y blindaje avanzado fue clave para que los Spartans pudieran operar en condiciones extremas y reaccionar con rapidez en combate. Su Ã©xito y dedicaciÃ³n le valieron la promociÃ³n para liderar el desarrollo de la armadura para los Spartan-III, donde enfrentÃ³ el reto de crear un diseÃ±o eficiente, econÃ³mico y adaptable para soldados con modificaciones genÃ©ticas y entrenamientos distintos a los Spartan-II. Gracias a sus esfuerzos, la UNSC pudo ampliar significativamente la producciÃ³n de super soldados, consolidando una ventaja tÃ¡ctica crucial en la guerra contra el Covenant. A pesar de sus logros, el Dr. Cervant sentÃ­a que sus ideas quedaban limitadas dentro de la UNSC. DecidiÃ³ entonces desarrollar en secreto un arma experimental, llamada en clave Tormenta Estelar, diseÃ±ada para cambiar las reglas del combate mediante una descarga energÃ©tica masiva. Sin embargo, en una prueba privada junto a un pequeÃ±o equipo, cometiÃ³ un error crÃ­tico causado por su exceso de confianza, que provocÃ³ una explosiÃ³n devastadora que evaporÃ³ toda la zona, eliminando cualquier rastro suyo, de su equipo y del arma. La UNSC lo declarÃ³ desaparecido sin saber la verdad de lo ocurrido, y la Tormenta Estelar y sus investigaciones quedaron perdidas para siempre. A pesar de este trÃ¡gico final, el legado del Dr. Cervant perdura en las armaduras que ayudÃ³ a desarrollar, que continÃºan protegiendo y potenciando a los Spartans en su lucha por la humanidad.', 'imagenes_personajes/1000027249.jpg', 27, '2025-08-05 22:19:54'),
(10, '.,gato espacial', 'jkl', 'imagenes_personajes/gato.jpg', 26, '2025-08-05 08:23:11'),
(12, 'Amister 595', 'Criado y entrenado en el planeta Hyrus a una corta edad, despues de que su mundo natal fue destruido por el covenant, el spartan Amister 595 se convirtiÃ³ rapidamente en un excepcional spartan de tercera generaciÃ³n, sin embargo, su verdadera batalla comenzÃ³ en la invasiÃ³n de su nuevo hogar en Hyrus, ya que los desterrados, comandados por el jefe de guerra Decimus, empezaron una campaÃ±a genocida por todo el planeta asesinando a todo aquel que se cruce en su camino, el spartan lucha valientemente contra esta creciente amenaza, y aunque ha perdido a muchos miembros de su familia de guerreros en este conflicto, esto no ha quebrantado su resiliencia por proteger a aquellos que no pueden luchar por si mismos, asegura que darÃ¡ su vida por proteger su hogar, su gente, y sus hermanos de armas', 'imagenes_comunidad/1000156080.png', 13, '2025-08-05 20:16:47');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuario`
--

CREATE TABLE `usuario` (
  `id` int(11) NOT NULL,
  `nombre_usuario` varchar(100) DEFAULT NULL,
  `correo` varchar(100) DEFAULT NULL,
  `contrasena` varchar(255) DEFAULT NULL,
  `imagen_perfil` varchar(255) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Volcado de datos para la tabla `usuario`
--

INSERT INTO `usuario` (`id`, `nombre_usuario`, `correo`, `contrasena`, `imagen_perfil`) VALUES
(18, 'dotkras', 'aldo@gmail.com', '$2y$10$FZvYCn/31o5DpZV/Af8ePuzZuqlvXS9RbOPnuHBNEBgdr9y8qn7qS', 'imagenes_perfil/buzz.jfif'),
(13, 'Homero ', 'ancientbeyder@gmail.com', '$2y$10$STAkfya3KCGsap7PuGSaquy4FILaXlK34nDezkTRqa4fm/TIRO2bi', 'imagenes_perfil/1000155868.jpg'),
(14, 'K', 'km2281567@gmail.com', '$2y$10$Siam/7GK4oIb5BzyDJCFju.FwrEoYnhjm6PxVZEHNsXVWteP9DG.O', 'imagenes_perfil/1000037307.jpg'),
(15, 'Karen', 'lunafg712@gmail.com', '$2y$10$Nwo5yTW5CAZTIeZ.RwdQDubyPecBtdf2LgXXP94zcthVt4KoNHOyu', 'imagenes_perfil/perfil.jpg'),
(22, 'Miguel', 'lop@gmail.com', '$2y$10$pmd/FEjVYDdSrALpCCmXJObPXqARSc3mA3tHs/.u.7oLxDyycQ9di', 'imagenes_perfil/20250221_123805.jpg'),
(24, 'JuanG', 'grievousuni@gmail.com', '$2y$10$RglxCTGKmfx0v09GCf6bXurN8crqCPH67o0ObC1aywR4R.vgqcaca', 'imagenes_perfil/images (6).jpeg'),
(26, 'Karen', 'ana@gmail.com', '$2y$10$DT3NcPUrfxxEYyGHpag8zOKdTmM1xB7p4pBRKsIMz8KM3nvg0AAO6', 'imagenes_perfil/puerta 1.jpg'),
(27, 'Ancient_Bey900', 'gamercatz900@gmail.com', '$2y$10$bKgJ4Sop6HBAiUFG0JIgU.4o0shyLN25FK6sNhy/rpIRGKBU/as0G', 'imagenes_perfil/1000025521.jpg');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `comentarios`
--
ALTER TABLE `comentarios`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `InteligenciasArtificiales`
--
ALTER TABLE `InteligenciasArtificiales`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `personajes`
--
ALTER TABLE `personajes`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `personajescomunidad`
--
ALTER TABLE `personajescomunidad`
  ADD PRIMARY KEY (`id_personaje`),
  ADD KEY `id_usuario` (`id_usuario`);

--
-- Indices de la tabla `usuario`
--
ALTER TABLE `usuario`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `comentarios`
--
ALTER TABLE `comentarios`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=54;

--
-- AUTO_INCREMENT de la tabla `InteligenciasArtificiales`
--
ALTER TABLE `InteligenciasArtificiales`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- AUTO_INCREMENT de la tabla `personajes`
--
ALTER TABLE `personajes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=59;

--
-- AUTO_INCREMENT de la tabla `personajescomunidad`
--
ALTER TABLE `personajescomunidad`
  MODIFY `id_personaje` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;

--
-- AUTO_INCREMENT de la tabla `usuario`
--
ALTER TABLE `usuario`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=28;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
